### ISSUE TITLE
insingts-client can not work with python-requests 2.11 

### ISSUE THREAD

**Issue by chenlizhong** [redhataccess/insights-client#111]
**Error message:**

 self.prepare_headers(headers)\n', '  File "/usr/lib/python2.7/site-packages/requests/models.py", line 409, in prepare_headers\n    check_header_validity(header)\n', '  File "/usr/lib/python2.7/site-packages/requests/utils.py", line 800, in check_header_validity\n    "not %s" % (value, type(value)))\n', "InvalidHeader: Header value 0.96 must be of type str or bytes, not <type 'float'>\n"]

**Root Cause**
Non-strings for header values is not accepted by Requests from 2.11
See the issue:  https://github.com/requests/requests/issues/3477

In our code, it is float for duration.

In https://github.com/redhataccess/insights-client/blob/master/insights_client/connection.py

Line 782-783
headers = {'x-rh-collection-time': duration}
upload = self.session.post(upload_url, files=files, headers=headers)

**Comment by gravitypriest** [comment]
Fixed here: https://github.com/redhataccess/insights-client/commit/50498228de627296275d5df5a233f0de55f9e616
