### ISSUE TITLE
Change 402 verbiage in Client.

### ISSUE THREAD

**Issue by brantleyr** [redhataccess/insights-client#73]

**Comment by brantleyr** [comment]
We want the Payment Required to be more friendly.

"""
redhat-access-insights --register
ERROR: Upload failed!
Debug Information:
HTTP Status Code: 402
HTTP Status Text: Payment Required
['Traceback (most recent .......
"""

**Comment by lphiri** [comment]
@brantleyr  I think that message is coming from the (remote) API. Its a standard (default)  HTTP 402 message, probably coming from nodejs express stack.  Makes more sense to change the code/message  in the API.

**Comment by brantleyr** [comment]
d o n e
